### PR TITLE
Python 3 support.

### PR DESCRIPTION
**Pull request by grugnog**

### CODE REVIEW

**Comment by Nurdok** [comment]
@maraujop, is this going to be merged?

**Comment by rollcat** [comment]
Bump...

**Comment by maraujop** [comment]
I'm sorry, I'm no longer maintaining this project as you can probably imagine from its lack of activity. I'm willing to add maintainers to it or give it to anyone wanting to take care of it.

Cheers,
Miguel

**Comment by rollcat** [comment]
I'm willing to take over as the maintainer. Sent an email.

**Comment by rollcat** [comment]
There's another problem with getting the library to run with Python 3, the `get_token` method references the now-gone `basestring`. I'm merging this but also adding some other changes.

**Comment by grugnog** [comment]
Thanks!

**Pull request merged**
